openapi: '3.0.1'
info:
  title: Biblioteca_IFRN
  description: Esse é um projeto de desenvolvimento de uma API para biblioteca do IFRN. Esse projeto foi desenvolvido com o objetivo de treinar e avaliar os conhecimentos adquiridos na disciplina de progamação orientada a serviços do curso informática para internet.
  version: '1.1'
servers:
  - url: http://{host}:{porta}/api
    variables:
      host:
        default: localhost
      porta:
        default: '8000'
        
paths:
  /listar:
    get:
      summary: lista todos os livros
      description: 'Lista todos os livros'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                minItems: 0
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    titulo:
                      type: string
                    autor:
                      type: string
                    descricao:
                      type: string
                    editora:
                      type: string
                    genero:
                      type: string

  /cadastrar:
    post:
      summary: cadastra um livro
      description: 'Cadastrar um livro'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titulo:
                  type: string
                autor:
                  type: string
                descricao:
                  type: string
                editora:
                  type: string
                genero:
                  type: string
      responses:
        '201':
          description: Livro cadastrado

  /exibir/{id}:
    get:
      summary: exibir um livro
      description: 'Retorna as informações de um livro em específico'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 'ID do livro a ser exibido'
      responses:
        '200':
          description: Livro encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  titulo:
                    type: string
                  autor:
                    type: string
                  descricao:
                    type: string
                  editora:
                    type: string
                  genero:
                    type: string
        '502':
          description: O livro não existe
  /editar/{id}:
    put:
      summary: editar um livro
      description: edita um livro em especifico
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                  id:
                    type: integer
                  titulo:
                    type: string
                  autor:
                    type: string
                  descricao:
                    type: string
                  editora:
                    type: string
                  genero:
                    type: string
      responses:
        200:
          description: OK
        404:
          description: Publicação não encontrada.

  /remover/{id}:
    delete:
      summary: deletar um livro
      responses:
        200:
          description: OK
        404:
          description: Livro não encontrado
    